### ISSUE TITLE
update Nexus Repository and Sonatype IQ Server versions

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/sonatype-platform-reference#13]

**Comment by madpah** [comment]
From what to what @hboutemy ?

**Comment by hboutemy** [comment]
fo IQ Server, I don't see why we would not update to latest
for Nexus, given it is default value provided in `.env-example`, I think we can also go to latest: no reason to stay on OrientDB, isn't it?

**Comment by hboutemy** [comment]
once #17 is merged, we can test upgrqades
