### ISSUE TITLE
rename nexus-platform-reference to sonatype-platform-reference

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/sonatype-platform-reference#15]
as a continuation of #12

**Comment by madpah** [comment]
Should we include `docker-compose` or something else specific in the name too @hboutemy?

**Comment by hboutemy** [comment]
let's keep it simple: no

**Comment by madpah** [comment]
Then LGTM!

**Comment by hboutemy** [comment]
done, and moved to `main` branch instead of `master` while at it
