### ISSUE TITLE
direct profile works, but not proxied one

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/sonatype-platform-reference#26]
with proxied, issue accessing the database: need to investigate why

reproduce issue by clearing all data and starting from scratch:
```
\rm -rf data/*
cp .env-example .env ; [ $(uname -p) = "arm" ] && cat .env-example | sed 's/ORGANIZATION=sonatype/ORGANIZATION=sonatypecommunity/' > .env                                                                                                            
docker-compose --profile=proxied up
```

same with `direct` just works

**Comment by hboutemy** [comment]
@madpah help appreciated: I don't get network setup in `proxied` profile (which is sadly the profile proposed for copy/paste in README)

**Comment by madpah** [comment]
I can't be sure of the exact issue this issue refers to - but am going to create new issues for items I have found whilst investigating @hboutemy.

**Comment by madpah** [comment]
https://github.com/sonatype-nexus-community/sonatype-platform-reference/issues/27
